"""Column mixins and small helpers shared by every model."""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any

from sqlalchemy import DateTime, func, text
from sqlalchemy import Enum as SAEnum
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column


def utcnow() -> datetime:
    """Timezone-aware "now", used as the client-side default for timestamps."""
    return datetime.now(UTC)


def pg_enum(enum_cls: type[StrEnum], name: str) -> SAEnum:
    """Build a native PostgreSQL enum type that stores member *values*.

    Without ``values_callable`` SQLAlchemy persists member *names* (``CRITICAL``),
    which would make the stored data diverge from the API representation.
    """
    return SAEnum(
        enum_cls,
        name=name,
        native_enum=True,
        create_constraint=False,
        values_callable=lambda enum: [member.value for member in enum],
    )


def json_object(**kwargs: Any) -> Any:
    """Non-null JSONB column holding an object, defaulting to ``{}``."""
    return mapped_column(
        JSONB, nullable=False, default=dict, server_default=text("'{}'::jsonb"), **kwargs
    )


def json_array(**kwargs: Any) -> Any:
    """Non-null JSONB column holding an array, defaulting to ``[]``."""
    return mapped_column(
        JSONB, nullable=False, default=list, server_default=text("'[]'::jsonb"), **kwargs
    )


class UUIDPrimaryKeyMixin:
    """UUID primary key, generated by the database when the client omits one."""

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
        # Mixin columns otherwise sort after the model's own; keep the key first
        # and the timestamps last so the physical table reads naturally.
        sort_order=-100,
    )


class CreatedAtMixin:
    """Creation timestamp only, for append-only tables that are never updated."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utcnow,
        server_default=func.now(),
        index=True,
        sort_order=100,
    )


class TimestampMixin(CreatedAtMixin):
    """Creation and update timestamps, both stored as UTC-aware values."""

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utcnow,
        server_default=func.now(),
        onupdate=utcnow,
        sort_order=101,
    )
