"""add anomaly fingerprint

Gives the detection engine an idempotency key. Re-analysing an overlapping
window is normal -- a scheduled run and an analyst will both do it -- and
without this each pass would insert the same finding again.

The column is nullable so anomalies raised by hand are unaffected: PostgreSQL
permits repeated NULLs in a unique index.

Revision ID: e9e79a9db3fd
Revises: a50308d09ae3
Create Date: 2026-08-12 10:02:10.454552
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'e9e79a9db3fd'
down_revision: str | None = 'a50308d09ae3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anomalies', sa.Column('fingerprint', sa.String(length=64), nullable=True))
    op.create_unique_constraint(op.f('uq_anomalies_fingerprint'), 'anomalies', ['fingerprint'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_anomalies_fingerprint'), 'anomalies', type_='unique')
    op.drop_column('anomalies', 'fingerprint')
    # ### end Alembic commands ###
